WIDTH = 1280
HEIGHT = 720
FPS = 60
FLOOR_HEIGHT = 70
ACTUAL_HEIGHT = HEIGHT - FLOOR_HEIGHT
GRAVITY_ACCELERATION = 9.8
INVENTORY_SLOT_WIDTH = INVENTORY_SLOT_HEIGHT = 80
ITEM_WIDTH = ITEM_HEIGHT = 54
DEFAULT_AMMO_LOADED = 15
DEFAULT_AMMO_STORED = 30
